CREATE TABLE [dbo].[PURCHTB] (
    [ITEM_Id]       UNIQUEIDENTIFIER  NOT NULL,
    [PRODUCT_NAME]     VARCHAR (50)  NULL,
    [PRICE_PER_UNIT]   MONEY         NULL,
    [QUANTITY]         VARCHAR (50)  NULL,
    [WEIGHT_KG_LTRES]  NVARCHAR (50) NULL,
    [SUPPLIER]         VARCHAR (50)  NULL,
    [SUPPLIER_CONTACT] NUMERIC (18)  NULL,
    [DATE]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ITEM_Id] ASC)
);

