CREATE TABLE [dbo].[stock]
(
	[ITEM Id] INT NOT NULL PRIMARY KEY, 
    [ITEM NAME] VARCHAR(50) NULL, 
    [ITEM PRICE(VAT)] MONEY NULL, 
    [ITEM] NCHAR(10) NULL, 
    [TAX DEDUCTION] DECIMAL NULL, 
    [NETPRICE] NCHAR(10) NULL
)
